### ISSUE TITLE
Create Scraper

### ISSUE THREAD

**Issue by okellyeneko** [Conor-O-Mahony/DublinBikes#1]
The scraper should be automated to scrape data every 5 min and store it in the AWS db.

**Comment by okellyeneko** [comment]
Created this scraper to see data from JDCaux. However, we still have to automate it and find a way to send the data that we want to our database in the corresponding tables... (created one on AWS with mySQL)

**Comment by Conor-O-Mahony** [comment]
The previous problem with the Lambda function was that it had no internet access. Creating a new VPC group with a NAT gateway resolved the issue (https://repost.aws/knowledge-center/internet-access-lambda-function). There was also an issue where you could connect to the RDS database, but no schema existed which was resolved by issuing a SQL CREATE TABLE command to the server.

**Comment by Conor-O-Mahony** [comment]
The maximum value of a SQL int is 2147483647 which is too small to track time. Hence, it was changed to bigint. The lambda scraper is now fully automated on AWS.

**Comment by okellyeneko** [comment]
Created a crontab and set it to every 5 minutes. 

Upload scraper , dotenv, gitignore files to EC2 instance.
Created a scraper.log 
Up and running / storing data every 5 min into db
